---
- name: Create app user
  user:
    name: "app"
    shell: "/bin/bash"
    system: yes

- name: Create app directory
  file:
    path: "/opt/app"
    state: directory
    owner: "app"
    group: "app"

- name: Copy app on server
  copy:
    src: "app-linux-amd64"
    dest: "/opt/app/app-linux-amd64"
    mode: '0755'
    owner: "app"
    group: "app"

- name: Copy app's cert and key
  copy:
    src: "{{ item.name }}"
    dest: "/opt/app"
    owner: "app"
    group: "app"
    mode: "{{ item.mode }}"
  loop:
    - { name: "../../cockroachdb/files/ca.crt", mode: '0644'}
    - { name: "../../cockroachdb/files/client.abc.crt", mode: '0644'}
    - { name: "../../cockroachdb/files/client.abc.key", mode: '0600'}
  no_log: True

- name: Template app service
  template:
    src: "app.service.j2"
    dest: "/etc/systemd/system/app.service"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Start app service
  systemd:
    name: "app"
    state: "started"
    enabled: "yes"
    daemon_reload: "yes"
...